urls = {9: 'https://opentdb.com/api.php?amount=1&category=9&type=multiple',
        10: 'https://opentdb.com/api.php?amount=1&category=10&type=multiple',
        11: 'https://opentdb.com/api.php?amount=1&category=11&type=multiple',
        12: 'https://opentdb.com/api.php?amount=1&category=12&type=multiple',
        13: 'https://opentdb.com/api.php?amount=1&category=13&type=multiple',
        14: 'https://opentdb.com/api.php?amount=1&category=14&type=multiple',
        15: 'https://opentdb.com/api.php?amount=1&category=15&type=multiple',
        16: 'https://opentdb.com/api.php?amount=1&category=16&type=multiple',
        17: 'https://opentdb.com/api.php?amount=1&category=17&type=multiple',
        18: 'https://opentdb.com/api.php?amount=1&category=18&type=multiple',
        19: 'https://opentdb.com/api.php?amount=1&category=19&type=multiple',
        20: 'https://opentdb.com/api.php?amount=1&category=20&type=multiple',
        21: 'https://opentdb.com/api.php?amount=1&category=21&type=multiple',
        22: 'https://opentdb.com/api.php?amount=1&category=22&type=multiple',
        23: 'https://opentdb.com/api.php?amount=1&category=23&type=multiple',
        24: 'https://opentdb.com/api.php?amount=1&category=24&type=multiple',
        25: 'https://opentdb.com/api.php?amount=1&category=25&type=multiple',
        26: 'https://opentdb.com/api.php?amount=1&category=26&type=multiple',
        27: 'https://opentdb.com/api.php?amount=1&category=27&type=multiple',
        28: 'https://opentdb.com/api.php?amount=1&category=28&type=multiple',
        29: 'https://opentdb.com/api.php?amount=1&category=29&type=multiple',
        30: 'https://opentdb.com/api.php?amount=1&category=30&type=multiple',
        31: 'https://opentdb.com/api.php?amount=1&category=31&type=multiple',
        32: 'https://opentdb.com/api.php?amount=1&category=32&type=multiple',
}