urls = {"Any Category": "https://opentdb.com/api.php?amount=1&type=multiple",
        "General Knowledge": "https://opentdb.com/api.php?amount=1&category=9&type=multiple",
        "Entertainment: Books": "https://opentdb.com/api.php?amount=1&category=10&type=multiple",
        "Entertainment: Film": "https://opentdb.com/api.php?amount=1&category=11&type=multiple",
        "Entertainment: Music": "https://opentdb.com/api.php?amount=1&category=12&type=multiple",
        "Entertainment: Musicals & Theatres": "https://opentdb.com/api.php?amount=1&category=13&type=multiple",
        "Entertainment: Television": "https://opentdb.com/api.php?amount=1&category=14&type=multiple",
        "Entertainment: Video Games": "https://opentdb.com/api.php?amount=1&category=15&type=multiple",
        "Entertainment: Board Games": "https://opentdb.com/api.php?amount=1&category=16&type=multiple",
        "Science & Nature": "https://opentdb.com/api.php?amount=1&category=17&type=multiple",
        "Science: Computers": "https://opentdb.com/api.php?amount=1&category=18&type=multiple",
        "Science: Mathematics": "https://opentdb.com/api.php?amount=1&category=19&type=multiple",
        "Mythology": "https://opentdb.com/api.php?amount=1&category=20&type=multiple",
        "Sports": "https://opentdb.com/api.php?amount=1&category=21&type=multiple",
        "Geography": "https://opentdb.com/api.php?amount=1&category=22&type=multiple",
        "History": "https://opentdb.com/api.php?amount=1&category=23&type=multiple",
        "Politics": "https://opentdb.com/api.php?amount=1&category=24&type=multiple",
        "Art": "https://opentdb.com/api.php?amount=1&category=25&type=multiple",
        "Celebrities": "https://opentdb.com/api.php?amount=1&category=26&type=multiple",
        "Animals": "https://opentdb.com/api.php?amount=1&category=27&type=multiple",
        "Vehicles": "https://opentdb.com/api.php?amount=1&category=28&type=multiple",
        "Entertainment: Comics": "https://opentdb.com/api.php?amount=1&category=29&type=multiple",
        "Science: Gadgets": "https://opentdb.com/api.php?amount=1&category=30&type=multiple",
        "Entertainment: Japanese Anime & Manga": "https://opentdb.com/api.php?amount=1&category=31&type=multiple",
        "Entertainment: Cartoon & Animations": "https://opentdb.com/api.php?amount=1&category=32&type=multiple"
        }